name: Qt6 CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - .gitignore
      - README.md

  pull_request:
    branches:
      - qt6
    paths-ignore:
      - .gitignore
      - README.md

concurrency:
  # cancel jobs on PRs only
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  QT_VERSION: 6.4.1

jobs:
  build:
    name: Build qios
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: source
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Download Qt (desktop)
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: ==3.0.*
          version: ${{ env.QT_VERSION }}
          target: desktop

      - name: Download Qt (iOS)
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: ==3.0.*
          version: ${{ env.QT_VERSION }}
          target: ios

      - name: Prepare Qt (iOS)
        run: |
          rm $Qt6_DIR/lib/cmake/Qt6Gui/Qt6QIOSIntegrationPlugin*
          rm $Qt6_DIR/lib/cmake/Qt6Gui/Qt6QIosOptionalPlugin_NSPhotoLibraryPlugin*

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Build qios
        run: |
          mkdir build && cd build
          qt-cmake ../source/ \
            -G"Ninja Multi-Config" \
            -DCMAKE_CONFIGURATION_TYPES="Release;Debug" \
            -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
            -DQT_HOST_PATH=$(readlink -f $Qt6_DIR/../macos)
          ninja
          DESTDIR=../install ninja install

      - name: Create artifacts
        run: |
          pushd install/Users/runner/work/qios
          tar cjvf ../../../../../qios.tar.bz2 Qt
          popd

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qios
          path: qios.tar.bz2

  release:
    name: Release qios
    if: github.ref_type == 'tag'
    runs-on: macos-12
    needs: build
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: qios

    - name: Make tarball
      env:
        TAG_NAME: ${{ github.ref_name }}
      run: |
        mv qios.tar.bz2 qios_${TAG_NAME}.tar.bz2

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: qios_${{ github.ref_name }}.tar.bz2
        allowUpdates: true
        draft: true
