name: Qt5 CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - .gitignore
      - README.md

  pull_request:
    branches:
      - qt5
    paths-ignore:
      - .gitignore
      - README.md

concurrency:
  # cancel jobs on PRs only
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  QT_VERSION: 5.15.2

jobs:
  build:
    name: Build qios
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: source
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Download Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: ==2.1.*
          version: ${{ env.QT_VERSION }}
          target: ios

      - name: Build qios
        run: |
          mkdir build && cd build
          qmake ../source/ios.pro
          make -j2
          INSTALL_ROOT=../install make install

      - name: Create artifacts
        run: |
          pushd install/Users/runner/work/qios
          tar cjvf ../../../../../qios.tar.bz2 Qt
          popd

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qios
          path: qios.tar.bz2

  release:
    name: Release qios
    if: github.ref_type == 'tag'
    runs-on: macos-12
    needs: build
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: qios

    - name: Make tarball
      env:
        TAG_NAME: ${{ github.ref_name }}
      run: |
        mv qios.tar.bz2 qios_${TAG_NAME}.tar.bz2
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: qios_${{ github.ref_name }}.tar.bz2
        allowUpdates: true
        draft: true
